# Cấu hình RAM cho Gradle (4GB là đủ và an toàn cho hầu hết máy)
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8

# Bắt buộc cho Flutter
android.useAndroidX=true

# Tắt Jetifier để build nhanh hơn (Nếu build lỗi thư viện cũ thì hãy bật lại thành true)
android.enableJetifier=false

# Tăng tốc độ build
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true

kotlin.incremental=false