// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMaAcnRna3WqW8ZqJRzHfhwm_lOYRYcsk',
    appId: '1:1078997756493:web:7fa96a1999d1323e690a04',
    messagingSenderId: '1078997756493',
    projectId: 'applgrs-e384d',
    authDomain: 'applgrs-e384d.firebaseapp.com',
    storageBucket: 'applgrs-e384d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApn87tAJi8DTFeqwfCcx46HB83ud_QNzk',
    appId: '1:1078997756493:android:9d351c5c3f1aad16690a04',
    messagingSenderId: '1078997756493',
    projectId: 'applgrs-e384d',
    storageBucket: 'applgrs-e384d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOhFmg0Is5j9TbMWIN54gdYoN0rpMgl_8',
    appId: '1:1078997756493:ios:1d64b5256ad076be690a04',
    messagingSenderId: '1078997756493',
    projectId: 'applgrs-e384d',
    storageBucket: 'applgrs-e384d.firebasestorage.app',
    androidClientId: '1078997756493-0k9uj8csoq5a8b0hp8ccnf8a7d34q975.apps.googleusercontent.com',
    iosClientId: '1078997756493-3fci3paoii3qr6pcl9cet1noia3pc4nr.apps.googleusercontent.com',
    iosBundleId: 'com.ecolive.converter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOhFmg0Is5j9TbMWIN54gdYoN0rpMgl_8',
    appId: '1:1078997756493:ios:8b729e0d2362a133690a04',
    messagingSenderId: '1078997756493',
    projectId: 'applgrs-e384d',
    storageBucket: 'applgrs-e384d.firebasestorage.app',
    androidClientId: '1078997756493-0k9uj8csoq5a8b0hp8ccnf8a7d34q975.apps.googleusercontent.com',
    iosClientId: '1078997756493-hr38g2bi9v5hu70nibdelb3ol7jvbqr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.splashScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMaAcnRna3WqW8ZqJRzHfhwm_lOYRYcsk',
    appId: '1:1078997756493:web:64fbb335bd01e201690a04',
    messagingSenderId: '1078997756493',
    projectId: 'applgrs-e384d',
    authDomain: 'applgrs-e384d.firebaseapp.com',
    storageBucket: 'applgrs-e384d.firebasestorage.app',
  );
}
